# Generated by Django 4.1.7 on 2023-03-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0002_rename_imagen_paciente_fotopaciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='id',
            new_name='ID',
        ),
    ]
