# Generated by Django 4.1.7 on 2023-03-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0011_rename_id_paciente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='Descripcion',
            new_name='Realiza',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Direccion',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='Telefono',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
