# Generated by Django 4.1.7 on 2023-03-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0012_rename_descripcion_paciente_realiza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Doctor', models.CharField(max_length=250)),
                ('Direccion', models.CharField(max_length=250)),
                ('Telefono', models.CharField(max_length=250)),
                ('FotoDoctor', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('Especialidad', models.TextField(null=True, verbose_name='Descripcion')),
            ],
        ),
    ]
