# Generated by Django 4.1.7 on 2023-03-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0013_doctores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctores',
            name='Especialidad',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Realiza',
            field=models.TextField(null=True, verbose_name=''),
        ),
    ]
