# Generated by Django 4.1.7 on 2023-03-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0014_alter_doctores_especialidad_alter_paciente_realiza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctores',
        ),
    ]
